#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
import agent

data = json.load(sys.stdin)

# Setup default values
ldap_domain = data.get("ldap_domain", "")
# bind user to the domain
if ldap_domain:
    agent.bind_user_domains([ldap_domain])
else:
    agent.bind_user_domains([])
#if ldap_domain != os.environ.get("LDAP_DOMAIN", ""):

# Setup LDAP domain
agent.set_env("LDAP_DOMAIN", ldap_domain)

# Setup cross domain authentication
cda = data.get("cda_status", False)
if cda:
    agent.set_env("CDA_STATUS", "True")
else:
    agent.set_env("CDA_STATUS", "False")

#  Setup SAML entity ID
saml_entity_id = data.get("saml_entity_id", "")
if saml_entity_id:
    agent.set_env("SAML_ENTITY_ID", saml_entity_id)
else:
    agent.set_env("SAML_ENTITY_ID", "")

# Setup issuerDBSAMLActivation
issuer_dbsaml_activation = data.get("saml_status", False)
if issuer_dbsaml_activation:
    agent.set_env("SAML_STATUS", "True")
else:
    agent.set_env("SAML_STATUS", "False")
