#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
import agent

data = json.load(sys.stdin)

# Setup default values
ldap_domain = data.get("ldap_domain", "")

# Bind user to the domain
agent.bind_user_domains([ldap_domain] if ldap_domain else [])

# Setup LDAP domain
agent.set_env("LDAP_DOMAIN", ldap_domain)

# Setup cross domain authentication
cda = data.get("cda_status", False)
agent.set_env("CDA_STATUS", "True" if cda else "False")

# Setup issuerDBSAMLActivation
saml = data.get("saml_status", False)
agent.set_env("SAML_STATUS", "True" if saml else "False")

# Setup sample apps visibility
sample_apps = data.get("sample_apps_enabled", False)
agent.set_env("SAMPLE_APPS_ENABLED", "True" if sample_apps else "False")
