#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
import agent

data = json.load(sys.stdin)

# Setup default values
ldap_domain = data.get("ldap_domain", "")
# bind user to the domain
if ldap_domain:
    agent.bind_user_domains([ldap_domain])
else:
    agent.bind_user_domains([])
#if ldap_domain != os.environ.get("LDAP_DOMAIN", ""):

# Setup LDAP domain
agent.set_env("LDAP_DOMAIN", ldap_domain)
