#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import agent

enabled = agent.read_envfile("smarthost.env").get("SMTP_ENABLED", "")

if enabled == "1":
    agent.run_helper("podman", "exec", "lemonldapng-app", "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli", "-yes" "1", "set", "SMTPAuthPass", "$SMTP_PASSWORD", "SMTPAuthUser", "$SMTP_USERNAME", "SMTPServer", "$SMTP_HOST", "SMTPTLS", "$SMTP_ENCRYPTION", "SMTPPort" "$SMTP_PORT")

