#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import agent

enabled = agent.read_envfile("smarthost.env").get("SMTP_ENABLED", "")
SMTPAuthPass = agent.read_envfile("smarthost.env").get("SMTP_PASSWORD", "")
SMTPAuthUser = agent.read_envfile("smarthost.env").get("SMTP_USERNAME", "")
SMTPServer = agent.read_envfile("smarthost.env").get("SMTP_HOST", "")
SMTPTLS = agent.read_envfile("smarthost.env").get("SMTP_ENCRYPTION", "")
SMTPPort = agent.read_envfile("smarthost.env").get("SMTP_PORT", "")

if enabled == "1":
    agent.run_helper("podman", "exec", "lemonldapng-app", "/usr/share/lemonldap-ng/bin/lemonldap-ng-cli", "-yes", "1", "set", "SMTPAuthPass", SMTPAuthPass, "SMTPAuthUser", SMTPAuthUser, "SMTPServer", SMTPServer, "SMTPTLS", SMTPTLS, "SMTPPort" , SMTPPort)

